### ISSUE TITLE
Conditional Job Support

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/api-preview-docs#49]
With current features we can use parameters to have [conditional workflows](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/conditional-workflows.md) and [conditional steps](https://circleci.com/docs/2.0/configuration-reference/#the-when-step-requires-version-21)

The latter (steps) gets a little ugly with the amount of nesting, but in the use case that I have an optional job I can work around this by redefining the entire workflow again, and include the extra job, but the permutations here could explode.

Use case - only publish asset when version is provided.

```
version: 2.1

parameters:
  publish_target:
    default: "" #empty values considered FALSEY
    type: string

workflows:
  basic:
    jobs:
      - sample_job:
          name: Build It
      - sample_job:
          name: Share It
          when: <<pipeline.parameters.publish_target>>
```
