### ISSUE TITLE
Invalid conditional workflow example

### ISSUE THREAD

**Issue by ilyapuchka** [CircleCI-Public/api-preview-docs#53]
In the example for conditional workflow there is a job that is conditionally added to the workflow based on parameter

```
workflows:
  version: 2
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - mytestjob
      - when:
          condition: << pipeline.parameters.deploy >>
          steps:
            - deploy
```

On practice though this results in the invalid configuration: `Cannot find a definition for job named when` when validated with `circleci 0.1.5830+2bb45a0`
