### ISSUE TITLE
Pipeline Parameters Ignored with API

### ISSUE THREAD

**Issue by philnielsen** [CircleCI-Public/api-preview-docs#67]
I'm having issues triggering jobs with pipeline parameters, I created a simplified example config to recreate.
config.yml
```yaml
version: 2.1
parameters:
  mark:
    type: boolean
    default: false

executors:
  go:
    docker:
      - image: circleci/golang

jobs:
  read-parameters:
    executor: go
    steps:
      - run: echo << pipeline.parameters.mark >>
workflows:
  version: 2
  if-mark:
    when: << pipeline.parameters.mark >>
    jobs:
      - read-parameters

  if-not-mark:
    unless: << pipeline.parameters.mark >>
    jobs:
      - read-parameters
```

Triggering with 
```bash
curl -u "${CIRCLECI_BOT_TOKEN}:" -d '{"parameters":{"mark":true}}' -X POST https://circleci.com/api/v2/project/:PROJECTSLUG/pipeline
```
or 
```bash
curl -u "${CIRCLECI_BOT_TOKEN}:" -d '{"parameters":{"mark":false}}' -X POST https://circleci.com/api/v2/project/:PROJECTSLUG/pipeline
```

always runs the `if-not-mark`, as configured above, but if I change the default value in the config it runs the `if-mark`, so I think it is an API issue.

Also I should add that i've been using this successfully before, so I think it is a regression with a recent behind the scenes update of v2. (I know its beta! 😁 )
